FROM node:26.4.0-slim@sha256:a1d9d671994fc2d26e297ac56b4b1522a8bc7fa71c43b14cd1b1fe6c5116f7dc

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package.json package-lock.json .npmrc ./

RUN npm install && \
    npm rebuild sharp --ignore-scripts=false

COPY ./ ./

EXPOSE 80

CMD ["npm", "run", "dev"]

HEALTHCHECK CMD curl -f http://localhost:80/healthz || exit 1
