services:
  close-powerlifting:
    container_name: close-powerlifting
    restart: unless-stopped
    init: true
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      DOCKER_CONTAINER: "true"
    networks:
      - close-powerlifting-network

networks:
  close-powerlifting-network:
    driver: bridge
