FROM node:24-alpine@sha256:d1b3b4da11eefd5941e7f0b9cf17783fc99d9c6fc34884a665f40a06dbdfc94f

RUN apk --no-cache add curl python3 make g++

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY ./ ./

EXPOSE 80

CMD ["npm", "run", "dev"]

HEALTHCHECK CMD curl -f http://localhost:80/api/health-check || exit 1
