FROM node:alpine

RUN apk --no-cache add curl

ENV ENV production

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

COPY ./ ./

RUN ls -a

# RUN npm ci --only=production
RUN npm install
RUN npm run build
# RUN npm run minify:html

EXPOSE 8080

CMD ["npm", "run", "start"]

HEALTHCHECK CMD curl -f http://localhost:8080/api/health-check || exit 1
