FROM node:16.17.0-bullseye-slim

ENV ENV production

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

COPY ./ ./

RUN npm ci --only=production
RUN npm run build

EXPOSE 8080

CMD ["npm", "run", "start"]