FROM node:26.3.0-slim@sha256:aa27a5fbf5acb298116a38133794f080406c6f8dfe52e2e2836bb55dc7cae8f0

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package.json package-lock.json .npmrc ./

RUN npm install && \
    npm rebuild sharp --ignore-scripts=false

COPY ./ ./

EXPOSE 80

CMD ["npm", "run", "dev"]

HEALTHCHECK CMD curl -f http://localhost:80/healthz || exit 1
